//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PostalZip { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public Nullable<int> List { get; set; }
        public string Text { get; set; }
        public Nullable<int> NumberRange { get; set; }
        public string Salary { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
    }
}
